### ISSUE TITLE
Installing an EasyVPK update to update itself doesn't work

### ISSUE THREAD

**Issue by Sarkie** [Electric1447/EasyVPK#3]
Trying to install 1.2.2 using EasyVPK seems to fail, what would be useful is keep the vpk in the VPK folder?

**Comment by Electric1447** [comment]
I disabled the ability to update EasyVPK within the app (you can still download the vpk)

**Comment by Electric1447** [comment]
I might add an updater in the future

**Comment by Sarkie** [comment]
No worries, I assumed it'd be hard. So have to create an external app

**Comment by Electric1447** [comment]
Added in v2.0.0
