### ISSUE TITLE
EasyVPK can't install apps if ioplus is enabled

### ISSUE THREAD

**Issue by takuhii** [Electric1447/EasyVPK#6]
If the ioplus plugin is enabled, then downloading vpks takes ages, and Installing the vpk results in a C-12828-1 error.

Personally I need ioplus to be active, bit can disable it if I need to use EasyVPK. But I shouldn't have to...

Any ideas?

**Comment by Electric1447** [comment]
I have ioplus installed I don't have this problem.

**Comment by Electric1447** [comment]
Unrelated, try to delete ux0:/data/EasyVPK folder.
