### ISSUE TITLE
EasyVPK crash with C2-12828-1

### ISSUE THREAD

**Issue by valentimarco** [Electric1447/EasyVPK#7]
I have a psvita with 3.68 H-encore and when i open the app, it's crash with the error C2-12828-1 and a "Saved Core File Succeded"
i downloaded the vpk  from https://vitadb.rinnegatamante.it/#/info/558.
https://file.io/ac1ojeWFM9bj the file that generates from the crash

**Comment by TBirdSoars** [comment]
I just started getting this same error, no idea why though. It worked just fine yesterday.

Edit: Deleting ux0:/data/EasyVPK folder worked, along with re-installing the latest version of EasyVPK.

**Comment by Perets21v** [comment]
Я тоже получил эту ошибку в EasyVPK, но я перепробывал все способы решения проблемы, но ничего не помогает что делать?

**Comment by Electric1447** [comment]
VitaDB changed domain, need to compile a new version with new api endpoint

**Comment by Perets21v** [comment]
А как это сделать?
